package com.example.manda.greenDao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.manda.Data.NewWordsData;
import com.example.manda.Data.userData;
import com.example.manda.Data.CourseInfo;

import com.example.manda.greenDao.db.NewWordsDataDao;
import com.example.manda.greenDao.db.userDataDao;
import com.example.manda.greenDao.db.CourseInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig newWordsDataDaoConfig;
    private final DaoConfig userDataDaoConfig;
    private final DaoConfig courseInfoDaoConfig;

    private final NewWordsDataDao newWordsDataDao;
    private final userDataDao userDataDao;
    private final CourseInfoDao courseInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        newWordsDataDaoConfig = daoConfigMap.get(NewWordsDataDao.class).clone();
        newWordsDataDaoConfig.initIdentityScope(type);

        userDataDaoConfig = daoConfigMap.get(userDataDao.class).clone();
        userDataDaoConfig.initIdentityScope(type);

        courseInfoDaoConfig = daoConfigMap.get(CourseInfoDao.class).clone();
        courseInfoDaoConfig.initIdentityScope(type);

        newWordsDataDao = new NewWordsDataDao(newWordsDataDaoConfig, this);
        userDataDao = new userDataDao(userDataDaoConfig, this);
        courseInfoDao = new CourseInfoDao(courseInfoDaoConfig, this);

        registerDao(NewWordsData.class, newWordsDataDao);
        registerDao(userData.class, userDataDao);
        registerDao(CourseInfo.class, courseInfoDao);
    }
    
    public void clear() {
        newWordsDataDaoConfig.clearIdentityScope();
        userDataDaoConfig.clearIdentityScope();
        courseInfoDaoConfig.clearIdentityScope();
    }

    public NewWordsDataDao getNewWordsDataDao() {
        return newWordsDataDao;
    }

    public userDataDao getUserDataDao() {
        return userDataDao;
    }

    public CourseInfoDao getCourseInfoDao() {
        return courseInfoDao;
    }

}
