package com.example.manda.greenDao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.manda.Data.NewWordsData;

import com.example.manda.greenDao.db.NewWordsDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig newWordsDataDaoConfig;

    private final NewWordsDataDao newWordsDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        newWordsDataDaoConfig = daoConfigMap.get(NewWordsDataDao.class).clone();
        newWordsDataDaoConfig.initIdentityScope(type);

        newWordsDataDao = new NewWordsDataDao(newWordsDataDaoConfig, this);

        registerDao(NewWordsData.class, newWordsDataDao);
    }
    
    public void clear() {
        newWordsDataDaoConfig.clearIdentityScope();
    }

    public NewWordsDataDao getNewWordsDataDao() {
        return newWordsDataDao;
    }

}
